In [2]:
# Ejercicio 2 — Series, Selección Condicional y Data Wrangling
import pandas as pd
import numpy as np
# Cargamos la nueva base de empleados (ya viene limpia)
df = pd.read_csv("empleados_technova_2024.csv")

df.info()   # 180 filas, 12 columnas, sin nulos -> no hay nada que limpiar

<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    180 non-null    int64
 1   nombre                180 non-null    str
 2   edad                  180 non-null    int64
 3   genero                180 non-null    str
 4   ciudad                180 non-null    str
 5   departamento          180 non-null    str
 6   modalidad             180 non-null    str
 7   nivel_educacion       180 non-null    str
 8   salario               180 non-null    float64
 9   fecha_ingreso         180 non-null    str
 10  evaluacion_desempeno  180 non-null    float64
 11  correo                180 non-null    str
dtypes: float64(2), int64(2), str(8)
memory usage: 17.0 KB

In [3]:
df.head()  # Vemos las primeras filas para entender la estructura de los datos

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
0,1,Ana Pérez,34,F,Santiago,Ventas,Híbrido,Universitario,850000.0,2020-03-15,4.2,ana.perez@technova.cl
1,2,Carlos Soto,28,M,Santiago,Ventas,Presencial,Técnico,1200000.0,2019-07-01,3.8,carlos.soto@technova.cl
2,3,María González,35,F,Santiago,Marketing,Remoto,Universitario,950000.0,2021-01-20,4.5,maria.gonzalez@technova.cl
3,4,Pedro Ramírez,45,M,Valparaíso,Ventas,Presencial,Media,1500000.0,2018-11-05,3.5,sin_correo
4,5,Lucía Fernández,35,F,Valparaíso,Marketing,Híbrido,Postgrado,1100000.0,2022-05-12,4.1,lucia.fernandez@technova.cl

In [4]:
# Series en Pandas
# Crear una serie
mini_serie = pd.Series(
    [85000, 1200000, 950000],
    index=["Ana", "Carlos", "María"],
    name="salarios"
)

mini_serie

Ana         85000
Carlos    1200000
María      950000
Name: salarios, dtype: int64

In [5]:
mini_serie.to_frame()  # Convertir la serie a un DataFrame

        salarios
Ana        85000
Carlos   1200000
María     950000

In [6]:
print("values: ", mini_serie.values)  # Valores de la serie
print("index: ", list(mini_serie.index))    # Índice de la serie
print("name: ", mini_serie.name)      # Nombre de la serie
print("dtype: ", mini_serie.dtype)    # Tipo de datos de la serie

values:  [  85000 1200000  950000]
index:  ['Ana', 'Carlos', 'María']
name:  salarios
dtype:  int64

In [7]:
columna_salario = df["salario"]  # Seleccionar la columna "salario" como una serie
print(type(columna_salario))  # Verificar que es una serie
columna_salario.head()  # Ver las primeras filas de la serie de salarios

<class 'pandas.Series'>

0     850000.0
1    1200000.0
2     950000.0
3    1500000.0
4    1100000.0
Name: salario, dtype: float64

In [8]:
# El guion bajo separador visual de miles
print(1_000_000 == 1000000)
print(1_000_000)

salario_sin = 12500000
salario_con = 12_500_000
print(salario_sin == salario_con)

True
1000000
True

In [9]:
# Las series vectorizadas
(df["salario"] / 1_000_000).head()  # Dividir la serie de salarios por un millón para convertir a millones

0    0.85
1    1.20
2    0.95
3    1.50
4    1.10
Name: salario, dtype: float64

In [10]:
print("promedio: ", df["salario"].mean())  # Calcular el salario promedio
print("mediana: ", df["salario"].median())  # Calcular la mediana de los salarios
print("máximo: ", df["salario"].max())  # Calcular el salario máximo
print("mínimo: ", df["salario"].min())  # Calcular el salario mínimo

# idmax() devolve el índice del salario máximo
fila_max = df["salario"].idxmax()
print("índice del salario máximo: ", fila_max)  # Imprimir el índice del salario máximo

# con .loc obtiene ese indice para ver quien es esa persona
df.loc[fila_max, ["nombre", "departamento", "salario"]]  # Ver la fila completa del empleado con el salario máximo

promedio:  1409333.3333333333
mediana:  1180000.0
máximo:  3930000.0
mínimo:  740000.0
índice del salario máximo:  87

nombre          Martina Bravo
departamento         Gerencia
salario             3930000.0
Name: 87, dtype: object

In [11]:
# Métodos de una serie para explorar valores

#* Valores distintos
print(df["departamento"].unique())  # Mostrar los departamentos únicos en la columna "departamento"

#* Cuenta cuantas veces aparece cada valor 
print(df["departamento"].value_counts())  # Contar cuántas veces aparece cada departamento en la columna "departamento"

print(df["departamento"].value_counts().sort_values())

<StringArray>
['Ventas', 'Marketing', 'Soporte', 'Gerencia', 'TI', 'RRHH']
Length: 6, dtype: str
departamento
Ventas       51
Soporte      44
TI           30
Marketing    27
Gerencia     19
RRHH          9
Name: count, dtype: int64
departamento
RRHH          9
Gerencia     19
Marketing    27
TI           30
Soporte      44
Ventas       51
Name: count, dtype: int64

### Ahora tú (1)
1. Guarda la columna `edad` en una variable y comprueba con `type()` que es una Serie.
2. ¿Cuál es la edad **promedio** de la empresa?

10:20 estamos de regreso para solucionar los primeros 2 puntos

3. ¿Quién es la persona **más joven**? (pista: `idxmin()` + `.loc`)
4. ¿Cuántas personas hay por `modalidad`? (pista: `value_counts()`)

In [12]:
edades = df["edad"]
print("1) tipo: ", type(edades))  # Verificar el tipo de la serie de edades

1) tipo:  <class 'pandas.Series'>

In [13]:
print("2) edad promedio: ", edades.mean().round(2))  # Calcular la edad promedio

2) edad promedio:  38.08

In [14]:

fila_joven = df["edad"].idxmin()  # Encontrar el índice de la persona más joven
print("3) persona más joven: ")
print(df.loc[fila_joven, ["nombre", "departamento", "edad"]])  # Mostrar el nombre, departamento y edad de la persona más joven

3) persona más joven:
nombre          Emilia Medina
departamento           Ventas
edad                       23
Name: 32, dtype: object

In [15]:
print("4) personas por modalidad de trabajo: ")
print(df["modalidad"].value_counts())  # Contar cuántas personas hay por cada modalidad de trabajo

4) personas por modalidad de trabajo:
modalidad
Presencial    80
Híbrido       56
Remoto        44
Name: count, dtype: int64

In [16]:
mascara = df["salario"] > 2_000_000
mascara.head()

0    False
1    False
2    False
3    False
4    False
Name: salario, dtype: bool

In [17]:
df[mascara].head()

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
7,8,Roberto Rojas,52,M,Antofagasta,Gerencia,Presencial,Postgrado,2500000.0,2017-02-14,4.6,roberto.rojas@technova.cl
11,13,Andrés López,41,M,Iquique,Gerencia,Presencial,Postgrado,2300000.0,2018-04-17,4.4,andres.lopez@technova.cl
16,18,Paula Morales,48,F,Antofagasta,Gerencia,Presencial,Postgrado,2400000.0,2016-08-21,4.7,paula.morales@technova.cl
20,22,Héctor Contreras,38,M,Valparaíso,Gerencia,Híbrido,Postgrado,3500000.0,2021-08-19,2.9,hector.contreras@technova.cl
25,27,Hernán Bravo,42,M,Concepción,Gerencia,Presencial,Postgrado,3210000.0,2023-11-25,3.8,hernan.bravo@technova.cl

In [18]:
df[df["salario"] > 2_000_000].head() # en una sola línea

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
7,8,Roberto Rojas,52,M,Antofagasta,Gerencia,Presencial,Postgrado,2500000.0,2017-02-14,4.6,roberto.rojas@technova.cl
11,13,Andrés López,41,M,Iquique,Gerencia,Presencial,Postgrado,2300000.0,2018-04-17,4.4,andres.lopez@technova.cl
16,18,Paula Morales,48,F,Antofagasta,Gerencia,Presencial,Postgrado,2400000.0,2016-08-21,4.7,paula.morales@technova.cl
20,22,Héctor Contreras,38,M,Valparaíso,Gerencia,Híbrido,Postgrado,3500000.0,2021-08-19,2.9,hector.contreras@technova.cl
25,27,Hernán Bravo,42,M,Concepción,Gerencia,Presencial,Postgrado,3210000.0,2023-11-25,3.8,hernan.bravo@technova.cl

In [19]:
# Operadores logicos, & (and), | (or), ~ (not)
# & (and) -> Y (ambas condiciones deben ser verdaderas)

# Personas del departamento de ventas en Santiago que ganan más de 1 millón
df[(df["departamento"] == "Ventas") & (df["ciudad"] == "Santiago") & (df["salario"] > 1_000_000)]

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
1,2,Carlos Soto,28,M,Santiago,Ventas,Presencial,Técnico,1200000.0,2019-07-01,3.8,carlos.soto@technova.cl
44,46,Francisco Navarro,30,M,Santiago,Ventas,Híbrido,Universitario,1150000.0,2021-12-16,2.9,francisco.navarro@technova.cl
45,47,Gonzalo Rodríguez,32,M,Santiago,Ventas,Presencial,Universitario,1400000.0,2017-10-10,3.5,gonzalo.rodriguez@technova.cl
62,64,Felipe Gutiérrez,29,M,Santiago,Ventas,Híbrido,Técnico,1090000.0,2018-11-01,3.5,felipe.gutierrez@technova.cl
64,66,Marcela Bravo,41,F,Santiago,Ventas,Presencial,Universitario,1160000.0,2020-07-23,3.4,marcela.bravo@technova.cl
67,69,Vicente Bustos,41,M,Santiago,Ventas,Híbrido,Postgrado,1360000.0,2022-05-28,3.5,vicente.bustos@technova.cl
68,70,Francisca Vergara,38,F,Santiago,Ventas,Presencial,Universitario,1360000.0,2018-08-05,2.3,francisca.vergara@technova.cl
74,76,Rodrigo Navarro,36,M,Santiago,Ventas,Presencial,Universitario,1160000.0,2021-10-27,3.5,rodrigo.navarro@technova.cl
91,93,Óscar Hernández,40,M,Santiago,Ventas,Presencial,Técnico,1170000.0,2016-06-08,3.8,oscar.hernandez@technova.cl
102,104,Josefa Tapia,39,F,Santiago,Ventas,Remoto,Postgrado,1560000.0,2017-12-20,3.9,josefa.tapia@technova.cl
110,112,Tomás Peña,43,M,Santiago,Ventas,Presencial,Universitario,1200000.0,2019-10-27,2.1,tomas.pena@technova.cl
117,119,Pilar Tapia,40,F,Santiago,Ventas,Presencial,Postgrado,1180000.0,2023-06-11,3.2,pilar.tapia@technova.cl
129,131,Catalina Fuentes,39,F,Santiago,Ventas,Presencial,Universitario,1220000.0,2017-05-12,3.3,catalina.fuentes@technova.cl
130,132,Consuelo Campos,43,F,Santiago,Ventas,Presencial,Universitario,1280000.0,2018-04-08,3.3,consuelo.campos@technova.cl
141,143,Andrea Parra,38,F,Santiago,Ventas,Remoto,Técnico,1140000.0,2020-01-04,2.8,andrea.parra@technova.cl
149,151,Trinidad Orellana,37,F,Santiago,Ventas,Híbrido,Técnico,1130000.0,2017-09-23,3.6,trinidad.orellana@technova.cl
171,173,Constanza Figueroa,30,F,Santiago,Ventas,Híbrido,Técnico,1090000.0,2021-04-20,3.1,constanza.figueroa@technova.cl
173,175,Paz Lagos,37,F,Santiago,Ventas,Remoto,Postgrado,1170000.0,2024-01-04,2.8,paz.lagos@technova.cl

In [20]:
# | (or) -> O (al menos una de las condiciones debe ser verdadera)
# Personas del departamento de Ventas o del departamento de Marketing
df[(df["departamento"] == "Ventas") | (df["departamento"] == "Marketing")]

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
0,1,Ana Pérez,34,F,Santiago,Ventas,Híbrido,Universitario,850000.0,2020-03-15,4.2,ana.perez@technova.cl
1,2,Carlos Soto,28,M,Santiago,Ventas,Presencial,Técnico,1200000.0,2019-07-01,3.8,carlos.soto@technova.cl
2,3,María González,35,F,Santiago,Marketing,Remoto,Universitario,950000.0,2021-01-20,4.5,maria.gonzalez@technova.cl
3,4,Pedro Ramírez,45,M,Valparaíso,Ventas,Presencial,Media,1500000.0,2018-11-05,3.5,sin_correo
4,5,Lucía Fernández,35,F,Valparaíso,Marketing,Híbrido,Postgrado,1100000.0,2022-05-12,4.1,lucia.fernandez@technova.cl
...,...,...,...,...,...,...,...,...,...,...,...,...
163,165,Isidora Fuentes,28,F,Valparaíso,Marketing,Híbrido,Universitario,1190000.0,2020-01-03,3.2,isidora.fuentes@technova.cl
168,170,Daniela Vergara,38,F,Santiago,Marketing,Híbrido,Media,1000000.0,2018-09-15,3.0,daniela.vergara@technova.cl
171,173,Constanza Figueroa,30,F,Santiago,Ventas,Híbrido,Técnico,1090000.0,2021-04-20,3.1,constanza.figueroa@technova.cl
172,174,Ximena Vidal,42,F,Valparaíso,Ventas,Remoto,Técnico,1020000.0,2018-12-08,3.6,ximena.vidal@technova.cl
173,175,Paz Lagos,37,F,Santiago,Ventas,Remoto,Postgrado,1170000.0,2024-01-04,2.8,paz.lagos@technova.cl

In [21]:
## ~ (not) -> NO (invierte la condición)

# Personas que No viven en Santiago
# ~ invierte la conndicion == 
fuera_santiago = df[~ (df["ciudad"] == "Santiago")]
print("personas que no viven en Santiago: ", len(fuera_santiago))

personas que no viven en Santiago:  103

In [22]:
# Obtener los que trabajan Remoto o Hibrido, pero que NO sean de gerencia
(df["departamento"] == "Gerencia")

0      False
1      False
2      False
3      False
4      False
       ...
175    False
176    False
177    False
178    False
179    False
Name: departamento, Length: 180, dtype: bool

In [23]:
~(df["departamento"] == "Gerencia") # con el ~ se invierte la condición, es decir, selecciona a los que NO son de gerencia

0      True
1      True
2      True
3      True
4      True
       ...
175    True
176    True
177    True
178    True
179    True
Name: departamento, Length: 180, dtype: bool

In [24]:
(df["modalidad"] == "Remoto") | (df["modalidad"] == "Híbrido")

0       True
1      False
2       True
3      False
4       True
       ...
175     True
176    False
177     True
178    False
179     True
Name: modalidad, Length: 180, dtype: bool

In [25]:
# Obtener los que trabajan Remoto o Hibrido, pero que NO sean de gerencia
flexibles = df[(df["modalidad"] == "Remoto") | (df["modalidad"] == "Híbrido") & ~(df["departamento"] == "Gerencia")]
print("personas que trabajan remoto o híbrido pero no son de gerencia: ", len(flexibles))
flexibles[["nombre", "departamento", "modalidad"]]

personas que trabajan remoto o híbrido pero no son de gerencia:  94

                  nombre departamento modalidad
0              Ana Pérez       Ventas   Híbrido
2         María González    Marketing    Remoto
4        Lucía Fernández    Marketing   Híbrido
8        Fernanda Torres    Marketing    Remoto
9           Diego Castro      Soporte   Híbrido
..                   ...          ...       ...
173            Paz Lagos       Ventas    Remoto
174       Marcela Medina           TI   Híbrido
175  Catalina Valenzuela      Soporte   Híbrido
177         Esteban Toro      Soporte    Remoto
179     Ignacia Gallardo           TI   Híbrido

[94 rows x 3 columns]

###  Ahora tu (combinando &, |, ~)
1. ¿Quienes son de **Ventas** **o** de **Soporte**? (pista: `|`)
2. ¿Quienes **no** trabajan de forma **Presencial**? (pista: `~` o `!=`)
3. Personas de **Santiago** que ganan mas de 1 millon **o** tienen evaluacion >= 4.5 (pista: combina `&`, `|` y muchos parentesis)

11:45 vamos con la solucion de estos 3 ejercicios

In [26]:
# 1 Personas de Ventas o Soporte (basta  con pertenecer a uno de los dos departamentos)
ventas_o_soporte = df[(df["departamento"] == "Ventas") | (df["departamento"] == "Soporte")]
print("1) personas de ventas o soporte: ", len(ventas_o_soporte), "personas")

1) personas de ventas o soporte:  95 personas

In [27]:
df["modalidad"] == "Presencial"

0      False
1       True
2      False
3       True
4      False
       ...
175    False
176     True
177    False
178     True
179    False
Name: modalidad, Length: 180, dtype: bool

In [28]:
# 2. Quienes No trabajan de forma Presencial (~ invierte la condición)
no_presencial = df[~(df["modalidad"] == "Presencial")]
print("2) personas que no trabajan de forma presencial: ", len(no_presencial), "personas")
no_presencial[["nombre", "departamento", "modalidad"]]

2) personas que no trabajan de forma presencial:  100 personas

                  nombre departamento modalidad
0              Ana Pérez       Ventas   Híbrido
2         María González    Marketing    Remoto
4        Lucía Fernández    Marketing   Híbrido
8        Fernanda Torres    Marketing    Remoto
9           Diego Castro      Soporte   Híbrido
..                   ...          ...       ...
173            Paz Lagos       Ventas    Remoto
174       Marcela Medina           TI   Híbrido
175  Catalina Valenzuela      Soporte   Híbrido
177         Esteban Toro      Soporte    Remoto
179     Ignacia Gallardo           TI   Híbrido

[100 rows x 3 columns]

In [29]:
# isin() -> para verificar si un valor está dentro de una lista de valores (evita encadenar múltiples condiciones con |)
df["ciudad"].isin(["Iquique", "Antofagasta"])

0      False
1      False
2      False
3      False
4      False
       ...
175    False
176    False
177    False
178    False
179    False
Name: ciudad, Length: 180, dtype: bool

In [30]:
df[df["ciudad"].isin(["Iquique", "Antofagasta"])]

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
7,8,Roberto Rojas,52,M,Antofagasta,Gerencia,Presencial,Postgrado,2500000.0,2017-02-14,4.6,roberto.rojas@technova.cl
10,11,Valentina Silva,29,F,Iquique,Ventas,Presencial,Técnico,880000.0,2022-08-23,4.0,valentina.silva@technova.cl
11,13,Andrés López,41,M,Iquique,Gerencia,Presencial,Postgrado,2300000.0,2018-04-17,4.4,andres.lopez@technova.cl
15,17,Matías Herrera,33,M,Antofagasta,Soporte,Presencial,Media,830000.0,2019-05-09,3.1,matias.herrera@technova.cl
16,18,Paula Morales,48,F,Antofagasta,Gerencia,Presencial,Postgrado,2400000.0,2016-08-21,4.7,paula.morales@technova.cl
19,21,Alejandra Navarro,32,F,Antofagasta,Ventas,Presencial,Técnico,1140000.0,2016-05-10,4.2,alejandra.navarro@technova.cl
26,28,Esteban Orellana,38,M,Antofagasta,Gerencia,Híbrido,Postgrado,3080000.0,2024-10-15,4.0,esteban.orellana@technova.cl
27,29,Maximiliano Salazar,35,M,Iquique,Soporte,Presencial,Universitario,1250000.0,2016-10-27,4.3,maximiliano.salazar@technova.cl
29,31,Manuel Martínez,30,M,Antofagasta,Ventas,Remoto,Técnico,970000.0,2021-06-21,4.3,manuel.martinez@technova.cl
35,37,Bárbara Carrasco,36,F,Iquique,Ventas,Híbrido,Técnico,1000000.0,2020-03-09,4.5,barbara.carrasco@technova.cl
37,39,Joaquín Valenzuela,42,M,Antofagasta,Soporte,Presencial,Postgrado,1280000.0,2021-12-11,3.2,joaquin.valenzuela@technova.cl
46,48,Paulina Rodríguez,24,F,Iquique,Marketing,Remoto,Universitario,1150000.0,2023-04-05,2.7,paulina.rodriguez@technova.cl
47,49,Consuelo Gutiérrez,45,F,Iquique,TI,Remoto,Universitario,1780000.0,2020-12-14,3.3,consuelo.gutierrez@technova.cl
49,51,Renata Valenzuela,27,F,Antofagasta,Marketing,Híbrido,Media,870000.0,2024-06-26,2.9,renata.valenzuela@technova.cl
52,54,Iván Orellana,39,M,Iquique,Gerencia,Presencial,Postgrado,3070000.0,2022-10-15,3.8,ivan.orellana@technova.cl
58,60,Manuel Peña,41,M,Antofagasta,Ventas,Híbrido,Universitario,1110000.0,2024-11-09,2.8,manuel.pena@technova.cl
63,65,Tamara Leiva,50,F,Antofagasta,Ventas,Híbrido,Técnico,1150000.0,2016-06-20,2.9,tamara.leiva@technova.cl
66,68,Patricio Gutiérrez,47,M,Antofagasta,Soporte,Presencial,Técnico,890000.0,2020-09-01,4.0,patricio.gutierrez@technova.cl
77,79,Constanza Carrasco,34,F,Antofagasta,Soporte,Remoto,Universitario,1230000.0,2016-05-16,3.7,constanza.carrasco@technova.cl
81,83,Bárbara Contreras,33,F,Iquique,TI,Remoto,Técnico,1680000.0,2018-03-27,3.1,barbara.contreras@technova.cl
87,89,Martina Bravo,50,F,Antofagasta,Gerencia,Remoto,Postgrado,3930000.0,2018-05-03,3.7,martina.bravo@technova.cl
90,92,Loreto Sandoval,44,F,Iquique,Soporte,Presencial,Postgrado,1330000.0,2020-05-21,4.1,loreto.sandoval@technova.cl
97,99,Esteban Maldonado,38,M,Iquique,Gerencia,Presencial,Postgrado,3150000.0,2023-03-19,2.5,esteban.maldonado@technova.cl
99,101,Cristian Toro,44,M,Antofagasta,TI,Remoto,Universitario,1790000.0,2021-03-27,3.2,cristian.toro@technova.cl
108,110,Daniela Bustos,45,F,Antofagasta,RRHH,Presencial,Técnico,1090000.0,2019-04-17,3.4,daniela.bustos@technova.cl
126,128,Alejandra Pizarro,38,F,Antofagasta,Gerencia,Híbrido,Postgrado,3850000.0,2017-05-08,3.7,sin_correo
127,129,Vicente Tapia,29,M,Antofagasta,Ventas,Presencial,Universitario,1150000.0,2021-02-09,3.4,vicente.tapia@technova.cl
134,136,Tomás Campos,30,M,Antofagasta,Marketing,Híbrido,Técnico,1150000.0,2018-04-25,4.6,tomas.campos@technova.cl
135,137,Paz Valenzuela,47,F,Antofagasta,Ventas,Presencial,Universitario,1260000.0,2018-12-20,3.5,paz.valenzuela@technova.cl
136,138,Sofía Fuentes,38,F,Antofagasta,Ventas,Presencial,Técnico,1000000.0,2023-03-16,2.4,sofia.fuentes@technova.cl
139,141,Mauricio Espinoza,34,M,Iquique,TI,Remoto,Postgrado,1860000.0,2023-11-28,2.4,mauricio.espinoza@technova.cl
142,144,Joaquín Medina,31,M,Iquique,TI,Remoto,Media,1160000.0,2023-11-10,4.3,joaquin.medina@technova.cl
145,147,Vicente Saavedra,36,M,Iquique,Soporte,Presencial,Postgrado,1320000.0,2021-02-01,3.7,vicente.saavedra@technova.cl
150,152,Josefa Vidal,47,F,Iquique,Soporte,Híbrido,Universitario,1010000.0,2020-01-06,3.0,josefa.vidal@technova.cl
157,159,Paz Araya,46,F,Antofagasta,Ventas,Remoto,Universitario,1230000.0,2017-09-17,3.5,paz.araya@technova.cl
160,162,Boris Maldonado,50,M,Antofagasta,Soporte,Presencial,Técnico,1020000.0,2017-02-27,4.7,boris.maldonado@technova.cl
162,164,Consuelo Toro,38,F,Antofagasta,Gerencia,Presencial,Universitario,2680000.0,2024-01-29,3.7,consuelo.toro@technova.cl

In [31]:
df[df["edad"].isin([25, 30, 40])]

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
29,31,Manuel Martínez,30,M,Antofagasta,Ventas,Remoto,Técnico,970000.0,2021-06-21,4.3,manuel.martinez@technova.cl
44,46,Francisco Navarro,30,M,Santiago,Ventas,Híbrido,Universitario,1150000.0,2021-12-16,2.9,francisco.navarro@technova.cl
53,55,Magdalena Campos,40,F,Concepción,Ventas,Presencial,Universitario,1200000.0,2021-03-20,4.1,magdalena.campos@technova.cl
72,74,Gabriel Figueroa,40,M,Santiago,Gerencia,Híbrido,Postgrado,3870000.0,2016-03-26,3.0,gabriel.figueroa@technova.cl
91,93,Óscar Hernández,40,M,Santiago,Ventas,Presencial,Técnico,1170000.0,2016-06-08,3.8,oscar.hernandez@technova.cl
117,119,Pilar Tapia,40,F,Santiago,Ventas,Presencial,Postgrado,1180000.0,2023-06-11,3.2,pilar.tapia@technova.cl
134,136,Tomás Campos,30,M,Antofagasta,Marketing,Híbrido,Técnico,1150000.0,2018-04-25,4.6,tomas.campos@technova.cl
140,142,Nicolás Riquelme,40,M,La Serena,TI,Híbrido,Universitario,1520000.0,2024-03-23,3.0,nicolas.riquelme@technova.cl
143,145,Paz Flores,40,F,Santiago,TI,Híbrido,Media,1220000.0,2020-12-30,4.1,paz.flores@technova.cl
171,173,Constanza Figueroa,30,F,Santiago,Ventas,Híbrido,Técnico,1090000.0,2021-04-20,3.1,constanza.figueroa@technova.cl
176,178,Cristóbal Saavedra,30,M,Santiago,Soporte,Presencial,Media,740000.0,2022-03-17,5.0,cristobal.saavedra@technova.cl

In [32]:
ciudades_norte = ["Iquique", "Antofagasta", "Arica"]
df[df["ciudad"].isin(ciudades_norte)]

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
7,8,Roberto Rojas,52,M,Antofagasta,Gerencia,Presencial,Postgrado,2500000.0,2017-02-14,4.6,roberto.rojas@technova.cl
10,11,Valentina Silva,29,F,Iquique,Ventas,Presencial,Técnico,880000.0,2022-08-23,4.0,valentina.silva@technova.cl
11,13,Andrés López,41,M,Iquique,Gerencia,Presencial,Postgrado,2300000.0,2018-04-17,4.4,andres.lopez@technova.cl
15,17,Matías Herrera,33,M,Antofagasta,Soporte,Presencial,Media,830000.0,2019-05-09,3.1,matias.herrera@technova.cl
16,18,Paula Morales,48,F,Antofagasta,Gerencia,Presencial,Postgrado,2400000.0,2016-08-21,4.7,paula.morales@technova.cl
19,21,Alejandra Navarro,32,F,Antofagasta,Ventas,Presencial,Técnico,1140000.0,2016-05-10,4.2,alejandra.navarro@technova.cl
26,28,Esteban Orellana,38,M,Antofagasta,Gerencia,Híbrido,Postgrado,3080000.0,2024-10-15,4.0,esteban.orellana@technova.cl
27,29,Maximiliano Salazar,35,M,Iquique,Soporte,Presencial,Universitario,1250000.0,2016-10-27,4.3,maximiliano.salazar@technova.cl
29,31,Manuel Martínez,30,M,Antofagasta,Ventas,Remoto,Técnico,970000.0,2021-06-21,4.3,manuel.martinez@technova.cl
35,37,Bárbara Carrasco,36,F,Iquique,Ventas,Híbrido,Técnico,1000000.0,2020-03-09,4.5,barbara.carrasco@technova.cl
37,39,Joaquín Valenzuela,42,M,Antofagasta,Soporte,Presencial,Postgrado,1280000.0,2021-12-11,3.2,joaquin.valenzuela@technova.cl
46,48,Paulina Rodríguez,24,F,Iquique,Marketing,Remoto,Universitario,1150000.0,2023-04-05,2.7,paulina.rodriguez@technova.cl
47,49,Consuelo Gutiérrez,45,F,Iquique,TI,Remoto,Universitario,1780000.0,2020-12-14,3.3,consuelo.gutierrez@technova.cl
49,51,Renata Valenzuela,27,F,Antofagasta,Marketing,Híbrido,Media,870000.0,2024-06-26,2.9,renata.valenzuela@technova.cl
52,54,Iván Orellana,39,M,Iquique,Gerencia,Presencial,Postgrado,3070000.0,2022-10-15,3.8,ivan.orellana@technova.cl
58,60,Manuel Peña,41,M,Antofagasta,Ventas,Híbrido,Universitario,1110000.0,2024-11-09,2.8,manuel.pena@technova.cl
63,65,Tamara Leiva,50,F,Antofagasta,Ventas,Híbrido,Técnico,1150000.0,2016-06-20,2.9,tamara.leiva@technova.cl
66,68,Patricio Gutiérrez,47,M,Antofagasta,Soporte,Presencial,Técnico,890000.0,2020-09-01,4.0,patricio.gutierrez@technova.cl
77,79,Constanza Carrasco,34,F,Antofagasta,Soporte,Remoto,Universitario,1230000.0,2016-05-16,3.7,constanza.carrasco@technova.cl
81,83,Bárbara Contreras,33,F,Iquique,TI,Remoto,Técnico,1680000.0,2018-03-27,3.1,barbara.contreras@technova.cl
87,89,Martina Bravo,50,F,Antofagasta,Gerencia,Remoto,Postgrado,3930000.0,2018-05-03,3.7,martina.bravo@technova.cl
90,92,Loreto Sandoval,44,F,Iquique,Soporte,Presencial,Postgrado,1330000.0,2020-05-21,4.1,loreto.sandoval@technova.cl
97,99,Esteban Maldonado,38,M,Iquique,Gerencia,Presencial,Postgrado,3150000.0,2023-03-19,2.5,esteban.maldonado@technova.cl
99,101,Cristian Toro,44,M,Antofagasta,TI,Remoto,Universitario,1790000.0,2021-03-27,3.2,cristian.toro@technova.cl
108,110,Daniela Bustos,45,F,Antofagasta,RRHH,Presencial,Técnico,1090000.0,2019-04-17,3.4,daniela.bustos@technova.cl
126,128,Alejandra Pizarro,38,F,Antofagasta,Gerencia,Híbrido,Postgrado,3850000.0,2017-05-08,3.7,sin_correo
127,129,Vicente Tapia,29,M,Antofagasta,Ventas,Presencial,Universitario,1150000.0,2021-02-09,3.4,vicente.tapia@technova.cl
134,136,Tomás Campos,30,M,Antofagasta,Marketing,Híbrido,Técnico,1150000.0,2018-04-25,4.6,tomas.campos@technova.cl
135,137,Paz Valenzuela,47,F,Antofagasta,Ventas,Presencial,Universitario,1260000.0,2018-12-20,3.5,paz.valenzuela@technova.cl
136,138,Sofía Fuentes,38,F,Antofagasta,Ventas,Presencial,Técnico,1000000.0,2023-03-16,2.4,sofia.fuentes@technova.cl
139,141,Mauricio Espinoza,34,M,Iquique,TI,Remoto,Postgrado,1860000.0,2023-11-28,2.4,mauricio.espinoza@technova.cl
142,144,Joaquín Medina,31,M,Iquique,TI,Remoto,Media,1160000.0,2023-11-10,4.3,joaquin.medina@technova.cl
145,147,Vicente Saavedra,36,M,Iquique,Soporte,Presencial,Postgrado,1320000.0,2021-02-01,3.7,vicente.saavedra@technova.cl
150,152,Josefa Vidal,47,F,Iquique,Soporte,Híbrido,Universitario,1010000.0,2020-01-06,3.0,josefa.vidal@technova.cl
157,159,Paz Araya,46,F,Antofagasta,Ventas,Remoto,Universitario,1230000.0,2017-09-17,3.5,paz.araya@technova.cl
160,162,Boris Maldonado,50,M,Antofagasta,Soporte,Presencial,Técnico,1020000.0,2017-02-27,4.7,boris.maldonado@technova.cl
162,164,Consuelo Toro,38,F,Antofagasta,Gerencia,Presencial,Universitario,2680000.0,2024-01-29,3.7,consuelo.toro@technova.cl

In [45]:
# Personas de Santiago que ganan mas de 1 millon o tienen evaluacion >= 4.5
df[(df["ciudad"] == "Santiago") & ((df["salario"] > 1_000_000) | (df["evaluacion_desempeno"] >= 4.5))]

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
1,2,Carlos Soto,28,M,Santiago,Ventas,Presencial,Técnico,1200000.0,2019-07-01,3.8,carlos.soto@technova.cl
2,3,María González,35,F,Santiago,Marketing,Remoto,Universitario,950000.0,2021-01-20,4.5,maria.gonzalez@technova.cl
18,20,Ximena Carrasco,39,F,Santiago,TI,Híbrido,Universitario,1670000.0,2020-03-19,3.7,ximena.carrasco@technova.cl
21,23,Florencia Bravo,33,F,Santiago,Marketing,Remoto,Postgrado,1490000.0,2022-04-23,3.6,florencia.bravo@technova.cl
28,30,Ricardo Orellana,41,M,Santiago,Ventas,Remoto,Técnico,970000.0,2023-02-09,4.5,ricardo.orellana@technova.cl
33,35,Paulina Araya,45,F,Santiago,Marketing,Híbrido,Postgrado,1570000.0,2018-06-16,3.8,paulina.araya@technova.cl
36,38,Catalina Parra,38,F,Santiago,Gerencia,Presencial,Universitario,3470000.0,2016-06-20,4.3,catalina.parra@technova.cl
38,40,Felipe Carrasco,29,M,Santiago,Soporte,Presencial,Postgrado,1380000.0,2018-06-04,2.9,felipe.carrasco@technova.cl
43,45,Fernando García,48,M,Santiago,TI,Remoto,Universitario,1770000.0,2017-06-24,4.4,fernando.garcia@technova.cl
44,46,Francisco Navarro,30,M,Santiago,Ventas,Híbrido,Universitario,1150000.0,2021-12-16,2.9,francisco.navarro@technova.cl
45,47,Gonzalo Rodríguez,32,M,Santiago,Ventas,Presencial,Universitario,1400000.0,2017-10-10,3.5,gonzalo.rodriguez@technova.cl
55,57,Raúl Pizarro,37,M,Santiago,Marketing,Híbrido,Técnico,1020000.0,2022-07-25,2.9,raul.pizarro@technova.cl
60,62,Ricardo Campos,34,M,Santiago,Marketing,Presencial,Universitario,1210000.0,2023-02-19,3.4,ricardo.campos@technova.cl
61,63,Fernando Gallardo,28,M,Santiago,TI,Remoto,Técnico,1390000.0,2024-01-19,3.5,fernando.gallardo@technova.cl
62,64,Felipe Gutiérrez,29,M,Santiago,Ventas,Híbrido,Técnico,1090000.0,2018-11-01,3.5,felipe.gutierrez@technova.cl
64,66,Marcela Bravo,41,F,Santiago,Ventas,Presencial,Universitario,1160000.0,2020-07-23,3.4,marcela.bravo@technova.cl
65,67,Cristóbal Toro,29,M,Santiago,TI,Remoto,Postgrado,2190000.0,2018-04-13,4.1,cristobal.toro@technova.cl
67,69,Vicente Bustos,41,M,Santiago,Ventas,Híbrido,Postgrado,1360000.0,2022-05-28,3.5,vicente.bustos@technova.cl
68,70,Francisca Vergara,38,F,Santiago,Ventas,Presencial,Universitario,1360000.0,2018-08-05,2.3,francisca.vergara@technova.cl
72,74,Gabriel Figueroa,40,M,Santiago,Gerencia,Híbrido,Postgrado,3870000.0,2016-03-26,3.0,gabriel.figueroa@technova.cl
74,76,Rodrigo Navarro,36,M,Santiago,Ventas,Presencial,Universitario,1160000.0,2021-10-27,3.5,rodrigo.navarro@technova.cl
75,77,Manuel Pizarro,39,M,Santiago,Marketing,Presencial,Universitario,1420000.0,2017-09-04,3.6,manuel.pizarro@technova.cl
76,78,Jorge Pizarro,38,M,Santiago,TI,Remoto,Técnico,1700000.0,2016-07-21,4.3,jorge.pizarro@technova.cl
82,84,Marcelo Lagos,47,M,Santiago,TI,Remoto,Universitario,1810000.0,2016-08-14,4.0,marcelo.lagos@technova.cl
84,86,Agustín Bravo,46,M,Santiago,RRHH,Presencial,Universitario,1240000.0,2017-11-28,3.8,agustin.bravo@technova.cl
89,91,Cristian Riquelme,36,M,Santiago,TI,Híbrido,Postgrado,1960000.0,2021-03-22,2.8,cristian.riquelme@technova.cl
91,93,Óscar Hernández,40,M,Santiago,Ventas,Presencial,Técnico,1170000.0,2016-06-08,3.8,oscar.hernandez@technova.cl
92,94,Maximiliano Martínez,42,M,Santiago,Gerencia,Presencial,Universitario,3070000.0,2016-12-16,4.1,maximiliano.martinez@technova.cl
94,96,Tamara Carrasco,29,F,Santiago,RRHH,Híbrido,Universitario,1090000.0,2023-05-22,3.5,sin_correo
96,98,Luis Riquelme,29,M,Santiago,RRHH,Híbrido,Postgrado,1270000.0,2022-03-29,3.3,luis.riquelme@technova.cl
101,103,Verónica Valenzuela,23,F,Santiago,TI,Remoto,Postgrado,1740000.0,2024-05-27,3.0,veronica.valenzuela@technova.cl
102,104,Josefa Tapia,39,F,Santiago,Ventas,Remoto,Postgrado,1560000.0,2017-12-20,3.9,josefa.tapia@technova.cl
104,106,Rodrigo Cárdenas,28,M,Santiago,Marketing,Remoto,Técnico,1160000.0,2020-08-09,3.7,rodrigo.cardenas@technova.cl
107,109,Sofía Medina,35,F,Santiago,TI,Presencial,Técnico,1410000.0,2019-12-23,4.0,sofia.medina@technova.cl
110,112,Tomás Peña,43,M,Santiago,Ventas,Presencial,Universitario,1200000.0,2019-10-27,2.1,tomas.pena@technova.cl
114,116,Verónica Olivares,49,F,Santiago,Gerencia,Remoto,Universitario,3150000.0,2017-03-25,3.6,veronica.olivares@technova.cl
117,119,Pilar Tapia,40,F,Santiago,Ventas,Presencial,Postgrado,1180000.0,2023-06-11,3.2,pilar.tapia@technova.cl
118,120,Fernando Contreras,43,M,Santiago,Marketing,Remoto,Universitario,1400000.0,2016-03-12,4.1,fernando.contreras@technova.cl
121,123,Luis Aravena,44,M,Santiago,TI,Híbrido,Media,1330000.0,2017-01-18,2.7,luis.aravena@technova.cl
122,124,Karla Navarro,39,F,Santiago,Marketing,Híbrido,Técnico,1150000.0,2016-09-26,3.4,karla.navarro@technova.cl
124,126,Maximiliano Vega,50,M,Santiago,Soporte,Presencial,Universitario,1180000.0,2016-07-03,3.6,maximiliano.vega@technova.cl
125,127,Álvaro Sepúlveda,48,M,Santiago,TI,Remoto,Técnico,1630000.0,2017-07-22,3.5,alvaro.sepulveda@technova.cl
129,131,Catalina Fuentes,39,F,Santiago,Ventas,Presencial,Universitario,1220000.0,2017-05-12,3.3,catalina.fuentes@technova.cl
130,132,Consuelo Campos,43,F,Santiago,Ventas,Presencial,Universitario,1280000.0,2018-04-08,3.3,consuelo.campos@technova.cl
137,139,Luis Lagos,50,M,Santiago,Marketing,Remoto,Técnico,1190000.0,2018-08-03,4.2,luis.lagos@technova.cl
141,143,Andrea Parra,38,F,Santiago,Ventas,Remoto,Técnico,1140000.0,2020-01-04,2.8,andrea.parra@technova.cl
143,145,Paz Flores,40,F,Santiago,TI,Híbrido,Media,1220000.0,2020-12-30,4.1,paz.flores@technova.cl
149,151,Trinidad Orellana,37,F,Santiago,Ventas,Híbrido,Técnico,1130000.0,2017-09-23,3.6,trinidad.orellana@technova.cl
154,156,Agustín Contreras,39,M,Santiago,Marketing,Presencial,Universitario,1220000.0,2018-11-28,3.9,agustin.contreras@technova.cl
159,161,Rodrigo Rodríguez,27,M,Santiago,Marketing,Híbrido,Técnico,1150000.0,2020-11-30,3.4,rodrigo.rodriguez@technova.cl
164,166,Verónica Saavedra,36,F,Santiago,Soporte,Presencial,Universitario,1060000.0,2018-06-26,4.1,veronica.saavedra@technova.cl
167,169,Agustín Pizarro,44,M,Santiago,TI,Remoto,Postgrado,1930000.0,2023-02-25,3.6,agustin.pizarro@technova.cl
170,172,Luis Figueroa,43,M,Santiago,Soporte,Híbrido,Postgrado,1430000.0,2016-03-03,4.5,luis.figueroa@technova.cl
171,173,Constanza Figueroa,30,F,Santiago,Ventas,Híbrido,Técnico,1090000.0,2021-04-20,3.1,constanza.figueroa@technova.cl
173,175,Paz Lagos,37,F,Santiago,Ventas,Remoto,Postgrado,1170000.0,2024-01-04,2.8,paz.lagos@technova.cl
174,176,Marcela Medina,43,F,Santiago,TI,Híbrido,Universitario,1670000.0,2021-07-13,2.7,marcela.medina@technova.cl
176,178,Cristóbal Saavedra,30,M,Santiago,Soporte,Presencial,Media,740000.0,2022-03-17,5.0,cristobal.saavedra@technova.cl

In [46]:
# between
# edad entre 30 y 35 años (inclusive)   edad >= 30 y edad <= 35
df[df["edad"].between(30, 35)]

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
0,1,Ana Pérez,34,F,Santiago,Ventas,Híbrido,Universitario,850000.0,2020-03-15,4.2,ana.perez@technova.cl
2,3,María González,35,F,Santiago,Marketing,Remoto,Universitario,950000.0,2021-01-20,4.5,maria.gonzalez@technova.cl
4,5,Lucía Fernández,35,F,Valparaíso,Marketing,Híbrido,Postgrado,1100000.0,2022-05-12,4.1,lucia.fernandez@technova.cl
5,6,José Muñoz,35,M,Concepción,Soporte,Presencial,Técnico,780000.0,2020-09-30,3.2,jose.munoz@technova.cl
6,7,Carla Díaz,31,F,Concepción,Soporte,Presencial,Técnico,820000.0,2021-03-08,3.9,sin_correo
8,9,Fernanda Torres,35,F,Santiago,Marketing,Remoto,Universitario,990000.0,2023-06-01,3.7,fernanda.torres@technova.cl
12,14,Camila Vargas,35,F,Valparaíso,Soporte,Híbrido,Técnico,800000.0,2021-10-02,3.6,camila.vargas@technova.cl
15,17,Matías Herrera,33,M,Antofagasta,Soporte,Presencial,Media,830000.0,2019-05-09,3.1,matias.herrera@technova.cl
19,21,Alejandra Navarro,32,F,Antofagasta,Ventas,Presencial,Técnico,1140000.0,2016-05-10,4.2,alejandra.navarro@technova.cl
21,23,Florencia Bravo,33,F,Santiago,Marketing,Remoto,Postgrado,1490000.0,2022-04-23,3.6,florencia.bravo@technova.cl
22,24,Agustín Orellana,33,M,Concepción,TI,Híbrido,Universitario,1550000.0,2022-03-05,3.2,agustin.orellana@technova.cl
27,29,Maximiliano Salazar,35,M,Iquique,Soporte,Presencial,Universitario,1250000.0,2016-10-27,4.3,maximiliano.salazar@technova.cl
29,31,Manuel Martínez,30,M,Antofagasta,Ventas,Remoto,Técnico,970000.0,2021-06-21,4.3,manuel.martinez@technova.cl
34,36,Óscar Cárdenas,31,M,Santiago,RRHH,Presencial,Media,980000.0,2017-08-04,4.0,oscar.cardenas@technova.cl
44,46,Francisco Navarro,30,M,Santiago,Ventas,Híbrido,Universitario,1150000.0,2021-12-16,2.9,francisco.navarro@technova.cl
45,47,Gonzalo Rodríguez,32,M,Santiago,Ventas,Presencial,Universitario,1400000.0,2017-10-10,3.5,gonzalo.rodriguez@technova.cl
48,50,Amanda Vega,34,F,Concepción,Ventas,Híbrido,Universitario,1230000.0,2021-03-12,3.3,amanda.vega@technova.cl
60,62,Ricardo Campos,34,M,Santiago,Marketing,Presencial,Universitario,1210000.0,2023-02-19,3.4,ricardo.campos@technova.cl
70,72,Sofía Cortés,35,F,Valparaíso,Marketing,Presencial,Universitario,1200000.0,2023-07-25,3.3,sofia.cortes@technova.cl
77,79,Constanza Carrasco,34,F,Antofagasta,Soporte,Remoto,Universitario,1230000.0,2016-05-16,3.7,constanza.carrasco@technova.cl
79,81,Cristóbal Medina,32,M,La Serena,RRHH,Presencial,Universitario,1000000.0,2024-10-12,3.4,cristobal.medina@technova.cl
80,82,Maximiliano Espinoza,32,M,La Serena,Soporte,Híbrido,Media,880000.0,2017-11-10,3.9,maximiliano.espinoza@technova.cl
81,83,Bárbara Contreras,33,F,Iquique,TI,Remoto,Técnico,1680000.0,2018-03-27,3.1,barbara.contreras@technova.cl
100,102,Emilia Vergara,34,F,Concepción,TI,Presencial,Postgrado,1990000.0,2022-05-15,4.3,emilia.vergara@technova.cl
107,109,Sofía Medina,35,F,Santiago,TI,Presencial,Técnico,1410000.0,2019-12-23,4.0,sofia.medina@technova.cl
112,114,Maximiliano Araya,32,M,Santiago,Ventas,Remoto,Media,860000.0,2019-05-25,3.2,maximiliano.araya@technova.cl
128,130,Martina Figueroa,32,F,La Serena,Ventas,Presencial,Técnico,970000.0,2021-02-04,3.4,martina.figueroa@technova.cl
133,135,Loreto Lagos,31,F,Concepción,Soporte,Presencial,Técnico,990000.0,2017-09-27,3.3,loreto.lagos@technova.cl
134,136,Tomás Campos,30,M,Antofagasta,Marketing,Híbrido,Técnico,1150000.0,2018-04-25,4.6,tomas.campos@technova.cl
139,141,Mauricio Espinoza,34,M,Iquique,TI,Remoto,Postgrado,1860000.0,2023-11-28,2.4,mauricio.espinoza@technova.cl
142,144,Joaquín Medina,31,M,Iquique,TI,Remoto,Media,1160000.0,2023-11-10,4.3,joaquin.medina@technova.cl
148,150,Jorge Carrasco,33,M,Valparaíso,Soporte,Presencial,Postgrado,1260000.0,2019-12-24,3.0,jorge.carrasco@technova.cl
151,153,Karla Hernández,34,F,Concepción,Soporte,Presencial,Técnico,1000000.0,2020-08-03,4.5,karla.hernandez@technova.cl
158,160,Patricia Rodríguez,31,F,Santiago,Soporte,Presencial,Media,780000.0,2022-09-06,2.7,patricia.rodriguez@technova.cl
161,163,Gabriel Bustos,32,M,Santiago,Soporte,Presencial,Media,790000.0,2021-03-29,2.8,gabriel.bustos@technova.cl
171,173,Constanza Figueroa,30,F,Santiago,Ventas,Híbrido,Técnico,1090000.0,2021-04-20,3.1,constanza.figueroa@technova.cl
176,178,Cristóbal Saavedra,30,M,Santiago,Soporte,Presencial,Media,740000.0,2022-03-17,5.0,cristobal.saavedra@technova.cl

In [ ]:
# Objetivo: separar a los empleados que SÍ tienen correo de los que no.

In [ ]:
# Paso 1 creamos la mascara para los que no tienen correo
df["correo"] == "sin_correo"

0      False
1      False
2      False
3       True
4      False
       ...
175    False
176    False
177    False
178    False
179    False
Name: correo, Length: 180, dtype: bool

In [49]:
~(df["correo"] == "sin_correo")

0       True
1       True
2       True
3      False
4       True
       ...
175     True
176     True
177     True
178     True
179     True
Name: correo, Length: 180, dtype: bool

In [52]:
con_correo = df[~(df["correo"] == "sin_correo")]
print("personas con correo: ", len(con_correo), "| sin correo: ", len(df) - len(con_correo))

personas con correo:  172 | sin correo:  8

In [ ]:
# Query es un método que permite hacer consultas a un DataFrame utilizando una sintaxis similar a SQL, lo que puede hacer que las consultas sean más legibles y fáciles de escribir.

#df.query() 
df[(df["departamento"] == "TI") & (df["salario"] > 1_500_000)].head()
df.query('departamento == "TI" and salario > 1_500_000').head()
# Query los operadores logicos se escriben con palabras (and, or, not) en lugar de símbolos (&, |, ~) y las condiciones se escriben como una cadena de texto dentro del método query().

,id,nombre,edad,genero,ciudad,departamento,modalidad,nivel_educacion,salario,fecha_ingreso,evaluacion_desempeno,correo
18,20,Ximena Carrasco,39,F,Santiago,TI,Híbrido,Universitario,1670000.0,2020-03-19,3.7,ximena.carrasco@technova.cl
22,24,Agustín Orellana,33,M,Concepción,TI,Híbrido,Universitario,1550000.0,2022-03-05,3.2,agustin.orellana@technova.cl
43,45,Fernando García,48,M,Santiago,TI,Remoto,Universitario,1770000.0,2017-06-24,4.4,fernando.garcia@technova.cl
47,49,Consuelo Gutiérrez,45,F,Iquique,TI,Remoto,Universitario,1780000.0,2020-12-14,3.3,consuelo.gutierrez@technova.cl
50,52,Macarena Martínez,46,F,Concepción,TI,Remoto,Técnico,1530000.0,2021-10-17,3.6,macarena.martinez@technova.cl

In [ ]:
# Query los operadores logicos se escriben con palabras (and, or, not) en lugar de símbolos (&, |, ~) y las condiciones se escriben como una cadena de texto dentro del método query().

# Ejercicio Equivalente a: df[(df["departamento"] == "Ventas") | (df["departamento"] == "Marketing")]

In [70]:
ventas_o_marketing = df.query('departamento == "Ventas" or departamento == "Marketing"') 
print(f"Personas en Ventas o Marketing: {len(ventas_o_marketing)} de {len(df)} " f"({len(ventas_o_marketing)/len(df):.1%} del total)")

print("\nReparto por departamento: ")
print(ventas_o_marketing["departamento"].value_counts())

# Renderizacion
display(ventas_o_marketing[["nombre", "departamento", "salario"]].head())

Personas en Ventas o Marketing: 78 de 180 (43.3% del total)

Reparto por departamento:
departamento
Ventas       51
Marketing    27
Name: count, dtype: int64

            nombre departamento    salario
0        Ana Pérez       Ventas   850000.0
1      Carlos Soto       Ventas  1200000.0
2   María González    Marketing   950000.0
3    Pedro Ramírez       Ventas  1500000.0
4  Lucía Fernández    Marketing  1100000.0

In [75]:
# Querys acepta las sintaxis "in [lista]"
en_ciudades = df.query("ciudad in ['Santiago', 'Valparaíso', 'Concepción']")
print(f"Filas que cumplen: {len(en_ciudades)} de {len(df)} ({len(en_ciudades)/len(df):.1%} del total)")
print("\nCuántas personas hay en cada una de esas ciudades: ")
print(en_ciudades["ciudad"].value_counts())
display(en_ciudades[["nombre", "ciudad", "departamento"]].head())

Filas que cumplen: 130 de 180 (72.2% del total)

Cuántas personas hay en cada una de esas ciudades:
ciudad
Santiago      77
Concepción    31
Valparaíso    22
Name: count, dtype: int64

            nombre      ciudad departamento
0        Ana Pérez    Santiago       Ventas
1      Carlos Soto    Santiago       Ventas
2   María González    Santiago    Marketing
3    Pedro Ramírez  Valparaíso       Ventas
4  Lucía Fernández  Valparaíso    Marketing

In [80]:
# "not in" es el inverso: conserva las filas cuyo valor No está en la lista
# Equivalente a: df[~df["modalidad"].isin(["Presencial"])]
no_presencial = df.query("modalidad not in ['Presencial']")
print(f"Personas que no trabajan de forma presencial: {len(no_presencial)} de {len(df)} ({len(no_presencial)/len(df):.1%} del total)")
print(no_presencial["modalidad"].value_counts())
display(no_presencial[["nombre", "modalidad"]].head())

Personas que no trabajan de forma presencial: 100 de 180 (55.6% del total)
modalidad
Híbrido    56
Remoto     44
Name: count, dtype: int64

            nombre modalidad
0        Ana Pérez   Híbrido
2   María González    Remoto
4  Lucía Fernández   Híbrido
8  Fernanda Torres    Remoto
9     Diego Castro   Híbrido

In [91]:
# Referencia a varialbes externas en query
umbral_salario = 1_800_000
umbral_evaluacion = 4.0

# query
top = df.query("salario > @umbral_salario and evaluacion_desempeno >= @umbral_evaluacion")
top[["nombre", "salario", "evaluacion_desempeno"]].head()

print(f"Cumplen salario > {umbral_salario} y evaluación >= {umbral_evaluacion}: {len(top)} personas")

# En python 0 se evalua como False
# Cualquier numero distinto de 0 se evalua como True
if len(top):
    print(f"Salario promedio del grupo: {top['salario'].mean():,.0f}")
    print(f"Evaluación promedio del grupo: {top['evaluacion_desempeno'].mean():.2f}")
# El if es una protección para no calcular promedios sobre un grupo vacio
display(top[["nombre", "salario", "evaluacion_desempeno"]].head())

Cumplen salario > 1800000 y evaluación >= 4.0: 14 personas
Salario promedio del grupo: 2,725,714
Evaluación promedio del grupo: 4.25

              nombre    salario  evaluacion_desempeno
7      Roberto Rojas  2500000.0                   4.6
11      Andrés López  2300000.0                   4.4
16     Paula Morales  2400000.0                   4.7
26  Esteban Orellana  3080000.0                   4.0
30     Daniela Leiva  3640000.0                   4.1

In [98]:
# @ con una lista 
departamentos_incluidos = ["TI", "Soporte", "Gerencia"]
seleccion = df.query("departamento in @departamentos_incluidos")
# seleccion[["nombre", "departamento"]]
print(seleccion.groupby("departamento").size())
print(seleccion.groupby("departamento")["salario"].mean().round(0))

departamento
Gerencia    19
Soporte     44
TI          30
dtype: int64
departamento
Gerencia    3183684.0
Soporte     1026364.0
TI          1699667.0
Name: salario, dtype: float64

In [101]:
# Condición Compleja y Encadenamiento
# Query : Mujeres en modalidad Remoto o Híbrido con salario en un rango medio-alto y ordenadas por evaluación de mayor a menor
# un rango medio alto es aquel 1_000_000 <= salario <= 2_000_000

resultado = df.query("genero == 'Femenino' and modalidad in ['Remoto', 'Híbrido'] and salario.between(1_000_000, 2_000_000)"
).sort_values("evaluacion_desempeno", ascending=False)

print(f"Mujeres en Remoto/Híbrido con salario entre 1M y 2M: {len(resultado)} de {len(df)} ({len(resultado)/len(df):.1%} del total)")

Mujeres en Remoto/Híbrido con salario entre 1M y 2M: 0 de 180 (0.0% del total)